"""Core domain models for the backtester: Bars, Signals, and Trades."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from enum import Enum
from typing import Final

REQUIRED_COLUMNS: Final[tuple[str, ...]] = ("Open", "High", "Low", "Close", "Volume")
PRICE_COLUMNS: Final[tuple[str, ...]] = ("Open", "High", "Low", "Close")


@dataclass(frozen=True)
class OHLCVBar:
    """A single daily OHLCV bar."""

    date: date
    open: float
    high: float
    low: float
    close: float
    volume: float


class SignalAction(str, Enum):
    """Possible actions for a trading signal."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass(frozen=True)
class Signal:
    """A trading signal generated by a strategy."""
    date: datetime
    action: SignalAction
    price: float
    reason: str = ""


class TradeSide(str, Enum):
    """Direction of a trade."""
    BUY = "BUY"
    SELL = "SELL"


@dataclass(frozen=True)
class Trade:
    """An executed trade record."""
    date: datetime
    side: TradeSide
    quantity: int
    price: float
    commission: float
    slippage_cost: float
    portfolio_value_after: float

    @property
    def total_cost(self) -> float:
        """Calculate the total net cost or revenue of the trade including fees."""
        gross = self.quantity * self.price
        if self.side == TradeSide.BUY:
            return gross + self.commission + self.slippage_cost
        return gross - self.commission - self.slippage_cost
